/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package review1;
import com.sun.javafx.print.PrintHelper;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.RowSorter;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.TableModel;
import review1.Restaurant;

public class AdminForm extends javax.swing.JFrame {
DefaultTableModel Tablemodel = new  DefaultTableModel() ;
DefaultTableModel Tablemodel1 = new  DefaultTableModel() ;
    private int idRestaurant;
     private String nameRestaurant;
      private boolean search = false;
     private boolean Deleteclick = false;
     private boolean Updeatclick = false;
     private int alldata = 0 ;
    AdminService service = new AdminService();
   List<Restaurant> getall = new ArrayList<Restaurant>();
   
    public AdminForm(int x) {

        idRestaurant = x;

        initComponents();
    }
     public AdminForm(String y) {

        nameRestaurant = y;

        initComponents();
    }
    
    public AdminForm() throws SQLException {
        initComponents();
          
       
         
       
         
         
          
      
        
     
        
        
        
        
        
        
        
        
        
       /* try {
            db db = new db();

            PreparedStatement pst;
            Connection connection;
            connection = DriverManager.getConnection(db.url, db.username, db.password);
            Statement stmt = connection.createStatement();
            String countfromdatabase = service.getIdNameRestaurant();
            ResultSet rs = stmt.executeQuery(countfromdatabase);
            Show_Restaruant.setModel(DbUtils.resultSetToTableModel(rs));

        } catch (SQLException ex) {

        }*/
       
      
           
       
        
       
     
       
       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        SearchText = new javax.swing.JTextField();
        Search = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Show_Restaruant = new javax.swing.JTable();
        Delete = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        Refresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Home page");

        SearchText.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        Search.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        Update.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        Show_Restaruant.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Image"
            }
        ));
        Show_Restaruant.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                Show_RestaruantAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        Show_Restaruant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Show_RestaruantMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Show_RestaruantMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(Show_Restaruant);

        Delete.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Delete.setText("Delete");
        Delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteMouseClicked(evt);
            }
        });
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton4.setText("Add");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        Refresh.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Refresh.setText("Refresh");
        Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Update, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Delete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SearchText)
                        .addGap(18, 18, 18)
                        .addComponent(Search)
                        .addGap(18, 18, 18)
                        .addComponent(Refresh)))
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchText, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Update, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed

        
        DefaultTableModel model = (DefaultTableModel) Show_Restaruant.getModel();
         List<Restaurant> getselect = new ArrayList<Restaurant>();
         nameRestaurant = SearchText.getText();
         
          for(int i =0;i<getall.size();i++){
             if(getall.get(i).getNameRestaurant().equals(SearchText.getText())){
                 search = true;
                 break;
             }
         }
         
         if(search == true){
             String row[] = new String[3];
          model.addRow(row);
          for(int i =0;i<getall.size();i++){
              if(getall.get(i).getNameRestaurant().equals(SearchText.getText())){
               model.setRowCount(0);
               row[0] = ""+getall.get(i).getIDRestaurant();
               row[1] = getall.get(i).getNameRestaurant();
               row[2] = getall.get(i).getlinkImage();
              
              model.addRow(row);
              }
                
          }
         }
         else if(search == false){
        int confirm = JOptionPane.showConfirmDialog(this, "ไม่พบ  "+SearchText.getText()+"  ในฐานข้อมูล", "Home",JOptionPane.CLOSED_OPTION);
              
         }
        
    
        //String searchRestaurant =SearchText.getText() ;
        /*getselect = service.Search((nameRestaurant));
       
        if(getselect.equals(null)){
             getall = service.getData();
          
          String rw[] = new String[3];
          
          for(int i =0;i<getall.size();i++){
               rw[0] = ""+getall.get(i).getIDRestaurant();
               rw[1] = getall.get(i).getNameRestaurant();
               rw[2] = getall.get(i).getlinkImage();
              
              model.addRow(rw);      
          }
        }
        else{
            
            String row[] = new String[3];
          model.addRow(row);
          for(int i =0;i<getselect.size();i++){
               model.setRowCount(0);
               row[0] = ""+getselect.get(i).getIDRestaurant();
               row[1] = getselect.get(i).getNameRestaurant();
               row[2] = getselect.get(i).getlinkImage();
              
              model.addRow(row);
                
          }
          
        }  */ 
    }//GEN-LAST:event_SearchActionPerformed

    private void Show_RestaruantAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_Show_RestaruantAncestorAdded
            
        DefaultTableModel model = (DefaultTableModel) Show_Restaruant.getModel();
        
          String[] col = {"ID","Name","Image"};
           Tablemodel = new DefaultTableModel(col,0);
          
          getall = service.getData();
           alldata = getall.size();
          String rw[] = new String[3];
          
          for(int i =0;i<getall.size();i++){
               rw[0] = ""+getall.get(i).getIDRestaurant();
               rw[1] = getall.get(i).getNameRestaurant();
               rw[2] = getall.get(i).getlinkImage();
              
              model.addRow(rw);
                
          }
          
           
          
          
          
        
         
    }//GEN-LAST:event_Show_RestaruantAncestorAdded

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshActionPerformed
        DefaultTableModel model = (DefaultTableModel) Show_Restaruant.getModel();
        model.setRowCount(0);
          String[] col = {"ID","Name","Image"};
          
          Tablemodel = new DefaultTableModel(col,0);

          String rw[] = new String[3];
          
          for(int i =0;i<getall.size();i++){
               rw[0] = ""+getall.get(i).getIDRestaurant();
               rw[1] = getall.get(i).getNameRestaurant();
               rw[2] = getall.get(i).getlinkImage();
              
              model.addRow(rw);
                
          }
    }//GEN-LAST:event_RefreshActionPerformed

    private void Show_RestaruantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Show_RestaruantMouseClicked
        
        DefaultTableModel model = (DefaultTableModel) Show_Restaruant.getModel();
        
        int index = Show_Restaruant.getSelectedRow();
         
        model = (DefaultTableModel) Show_Restaruant.getModel();
        
         int value = Integer.parseInt(model.getValueAt(index, 0).toString());
         idRestaurant = value;
         System.out.println(idRestaurant);
       
        
    }//GEN-LAST:event_Show_RestaruantMouseClicked

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
         setVisible(false);
        UpdateRestaruant change = new UpdateRestaruant(idRestaurant);
        change.setVisible(true);        
        
             
         
        
         
         
          
        
    }//GEN-LAST:event_UpdateActionPerformed

    private void Show_RestaruantMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Show_RestaruantMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Show_RestaruantMouseEntered

    private void DeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMouseClicked
        // TODO add your handling code here:
        Deleteclick = true;
        
        int confirm = JOptionPane.showConfirmDialog(this, "What do you want to Delete Restaruant? ", "Confrim", JOptionPane.YES_NO_OPTION);
        if(confirm == JOptionPane.YES_OPTION){
            service.Delete(idRestaurant);
            confirm = JOptionPane.showConfirmDialog(this, "Delete Complete ", "Confrim", JOptionPane.CLOSED_OPTION);
        }
        else if(confirm == JOptionPane.NO_OPTION){
            
        }
        

        DefaultTableModel model = (DefaultTableModel) Show_Restaruant.getModel();
        model.setRowCount(0);
          String[] col = {"ID","Name","Image"};
           Tablemodel = new DefaultTableModel(col,0);
          
          getall = service.getData();
          
          String rw[] = new String[3];
          
          for(int i =0;i<getall.size();i++){
               rw[0] = ""+getall.get(i).getIDRestaurant();
               rw[1] = getall.get(i).getNameRestaurant();
               rw[2] = getall.get(i).getlinkImage();
              
              model.addRow(rw);
          }
             
          Deleteclick = false;
        
    }//GEN-LAST:event_DeleteMouseClicked

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        //service.Delete(idRestaurant);
    }//GEN-LAST:event_DeleteActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       
        setVisible(false);
        AddRestaruant change = new AddRestaruant();
        change.setVisible(true);
        
       
       
    }//GEN-LAST:event_jButton4ActionPerformed
   

        
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AdminForm().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(AdminForm.class.getName()).log(Level.SEVERE, null, ex);
                }
              
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.JButton Refresh;
    private javax.swing.JButton Search;
    private javax.swing.JTextField SearchText;
    private javax.swing.JTable Show_Restaruant;
    private javax.swing.JButton Update;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

   
}
