/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package review1;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import review1.Restaurant;

/**
 *
 * @author Evolution Gaming
 */
public class UpdateRestaruant extends javax.swing.JFrame {

    /**
     * Creates new form UpdateRestaruant
     */
    private int idRestaurant;
    ArrayList<Restaurant> selectupdate = new ArrayList<>();
    AdminService service = new AdminService();
    
         String Name = "";
         String address = "";
         String des = "";
         String Pro = "";
         int ne1 = 0;
         int ne2 = 0;
         int ne3 = 0;
         String Link = "";
         //---------------------------------------------------------------------
           String NameRestaurant = "";
         String AddressRestaurant = "";
         String DescribtionRestaurant = "";
         String Province = "";
         int Restarantnearby1 = 0;
         int Restarantnearby2 = 0;
         int Restarantnearby3 = 0;
         String linkImage = "";

    
    public UpdateRestaruant() {
       
        
        initComponents();
    }
        public UpdateRestaruant(int x) {
       
           idRestaurant = x;
       
           initComponents();
    }

  
        
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        Address = new javax.swing.JTextField();
        Des = new javax.swing.JTextField();
        pro = new javax.swing.JTextField();
        n2 = new javax.swing.JTextField();
        n3 = new javax.swing.JTextField();
        n1 = new javax.swing.JTextField();
        link = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setText("Update Restaurant");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Name Restaurant");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Descriptions Restaurant");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Address Restaurant");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Province");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Link Image (URL)");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Restaurant near by 2");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Restaurant near by 3");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Restaurant near by 1");

        name.setFont(new java.awt.Font("Angsana New", 0, 18)); // NOI18N
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        Address.setFont(new java.awt.Font("Angsana New", 0, 18)); // NOI18N

        Des.setFont(new java.awt.Font("Angsana New", 0, 18)); // NOI18N

        pro.setFont(new java.awt.Font("Angsana New", 0, 18)); // NOI18N

        n2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        n3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        n1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        link.setFont(new java.awt.Font("Angsana New", 0, 18)); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("Update");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(link, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(100, 100, 100)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(129, 129, 129)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(n1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(41, 41, 41)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(n3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel1)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(32, 32, 32)
                                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(32, 32, 32)
                                    .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(Des, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(n2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pro, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 100, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(461, 461, 461)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Des, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(pro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(n1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(n2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(n3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(link, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        
    }//GEN-LAST:event_formComponentShown

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
         
        
        selectupdate = service.Search(idRestaurant);
        for(int i =0;i<selectupdate.size();i++ ){
        Name = selectupdate.get(i).getNameRestaurant();
        address = (selectupdate.get(i).getAddressRestaurant());
         des = selectupdate.get(i).getDescribtionRestaurant();
         Pro = (selectupdate.get(i).getProvince());
          ne1 = (selectupdate.get(i).getRestarantnearby1());
          ne2 = (selectupdate.get(i).getRestarantnearby2());
          ne3 = (selectupdate.get(i).getRestarantnearby3());
          Link = (selectupdate.get(i).getlinkImage());
  
        }
        name.setText(Name);
        Address.setText(address);
        Des.setText(des);
        pro.setText(Pro);
        n1.setText(""+ne1);
        n2.setText(""+ne2);
        n3.setText(""+ne3);
        link.setText(Link);
        
    }//GEN-LAST:event_formWindowActivated

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        
    }//GEN-LAST:event_nameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Restaurant res = new Restaurant();
       NameRestaurant = name.getText();
       AddressRestaurant = Address.getText();
       DescribtionRestaurant = Des.getText();
       Province = pro.getText();
       Restarantnearby1 = Integer.parseInt(n1.getText());
       Restarantnearby2 = Integer.parseInt(n2.getText());
       Restarantnearby3 = Integer.parseInt(n3.getText());
       linkImage = link.getText();
       
       
       res.setNameRestaurant(NameRestaurant);
       res.setAddressRestaurant(AddressRestaurant);
       res.setDescribtionRestaurant(DescribtionRestaurant);
       res.setRestarantnearby1(Restarantnearby1);
       res.setRestarantnearby2(Restarantnearby2);
       res.setRestarantnearby3(Restarantnearby3);
       res.setProvince(Province);
       res.setlinkImage(linkImage);
       
      
       service.update(res, idRestaurant);
       
       int confirm = JOptionPane.showConfirmDialog(this, "Update Complete ", "Confrim", JOptionPane.CLOSED_OPTION);
       
         setVisible(false);
        AdminForm change = new AdminForm(idRestaurant);
        change.setVisible(true); 
        /*String NameRestaurant = Name;
        String AddressRestaurant = address ;
        String DescribtionRestaurant = des;
        String Province = Pro;
        int Restarantnearby1 = ne1;
       int Restarantnearby2 = ne2;
        int Restarantnearby3 = ne3;
        String linkImage = Link ;
        
         String NameRestaurant = "";
         String AddressRestaurant = "";
         String DescribtionRestaurant = "";
         String Province = "";
         int Restarantnearby1 = 0;
         int Restarantnearby2 = 0;
         int Restarantnearby3 = 0;
         String linkImage = "";
         int Count = 0;
         int Point = 0;
         double Rating ;
        
        
        
        
        NameRestaurant = name.getText();
       AddressRestaurant = Address.getText();
       DescribtionRestaurant = Des.getText();
       Province = pro.getText();
       Restarantnearby1 = Integer.parseInt(n1.getText());
       Restarantnearby2 = Integer.parseInt(n2.getText());
       Restarantnearby3 = Integer.parseInt(n3.getText());
       linkImage = link.getText();
       
       
        service.UpdateService(idRestaurant, NameRestaurant, AddressRestaurant, DescribtionRestaurant,  Restarantnearby1, Restarantnearby2, Restarantnearby3, Province,linkImage);
        System.out.println(NameRestaurant);
        System.out.println(AddressRestaurant);
        System.out.println(DescribtionRestaurant);
        System.out.println(Count);
        System.out.println(Point);
        System.out.println(Restarantnearby1);
        System.out.println(Restarantnearby2);
        System.out.println(Restarantnearby3);
        System.out.println(Province);
        System.out.println(Rating);
        System.out.println(linkImage);
        */
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
//        Restaurant res = new Restaurant();
//        
//        String NameRestaurant = Name;
//        String AddressRestaurant = address ;
//        String DescribtionRestaurant = des;
//        String Province = Pro;
//        int Restarantnearby1 = ne1;
//        int Restarantnearby2 = ne2;
//        int Restarantnearby3 = ne3;
//        String linkImage = Link ;
//        
//       NameRestaurant = name.getText();
//       AddressRestaurant = Address.getText();
//       DescribtionRestaurant = Des.getText();
//       Province = pro.getText();
//       Restarantnearby1 = Integer.parseInt(n1.getText());
//       Restarantnearby2 = Integer.parseInt(n2.getText());
//       Restarantnearby3 = Integer.parseInt(n3.getText());
//       linkImage = link.getText();
//       
//       
//       res.setNameRestaurant(NameRestaurant);
//       res.setAddressRestaurant(AddressRestaurant);
//       res.setDescribtionRestaurant(DescribtionRestaurant);
//       res.setRestarantnearby1(Restarantnearby1);
//       res.setRestarantnearby2(Restarantnearby2);
//       res.setRestarantnearby3(Restarantnearby3);
//       res.setProvince(Province);
//       res.setlinkImage(linkImage);
//       
//       service.update(res, idRestaurant);
//        System.out.println(idRestaurant);
       
//         service.UpdateService(idRestaurant, NameRestaurant, AddressRestaurant, DescribtionRestaurant,  Restarantnearby1, Restarantnearby2, Restarantnearby3, Province,linkImage);
        System.out.println(NameRestaurant);
        System.out.println(AddressRestaurant);
        System.out.println(DescribtionRestaurant);
        System.out.println(Restarantnearby1);
        System.out.println(Restarantnearby2);
        System.out.println(Restarantnearby3);
        System.out.println(Province);
        System.out.println(linkImage);
        
        
        
      
        
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateRestaruant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateRestaruant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateRestaruant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateRestaruant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateRestaruant().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Address;
    private javax.swing.JTextField Des;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField link;
    private javax.swing.JTextField n1;
    private javax.swing.JTextField n2;
    private javax.swing.JTextField n3;
    private javax.swing.JTextField name;
    private javax.swing.JTextField pro;
    // End of variables declaration//GEN-END:variables
}
